### PR TITLE
Fix typo in Felix's surname

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Review by Robinlovelace — APPROVED** [review]

**Comment by asinghvi17** [comment]
@Robinlovelace could you give @felixcremer, @rafaqz and I write access to this repo?  I believe that currently only Maarten has it.

**Comment by evetion** [comment]
Ouch, thanks!

**Comment by Robinlovelace** [comment]
> @Robinlovelace could you give @felixcremer, @rafaqz and I write access to this repo? I believe that currently only Maarten has it.

Will do..

**Comment by Robinlovelace** [comment]
Job done: https://github.com/geocompx/geocompjl/invitations

**Comment by felixcremer** [comment]
Thanks Anshul. Most likely I wouldn't have seen it by myself.

**Pull request merged**
